# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=None),
        ),
    ]
