# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsite', '0002_auto_20170312_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
